import Darwin
import Foundation

struct MacActiveCaptureCandidate: Equatable {
    let id: UUID
    let url: URL
    let createdAt: Date
}

struct MacActiveCaptureRecoveryReport {
    let recoveredRecords: [MacPendingAudioRecord]
    let failureDescriptions: [String]
}

struct MacPrivateTemporaryCleanupReport {
    let removedCount: Int
    let failureDescriptions: [String]
}

/// Finds only unfinished files created by `MacAudioRecorder`. Discovery is
/// intentionally narrower than a generic WAV scan: a candidate needs the exact
/// generated basename, private owner-only metadata, one regular-file link, a
/// RIFF/WAVE signature, and bytes beyond the canonical header.
enum MacActiveCaptureRecovery {
    private static let prefix = "ElevenLabs-"
    private static let suffix = ".wav"
    private static let uploadPrefix = "ElevenLabs-upload-"
    private static let uploadSuffix = ".multipart"
    private static let importPrefix = "ElevenLabs-import-"
    private static let importExtensions: Set<String> = [
        "wav", "mp3", "m4a", "mp4", "mov", "ogg", "opus", "flac", "aac",
        "aif", "aiff", "caf", "webm", "mkv", "mpeg", "mpg", "3gp", "3gpp",
        "wma", "amr",
    ]
    private static let minimumWAVHeaderSize: off_t = 44

    static func discover(
        in temporaryDirectoryURL: URL,
        fileManager: FileManager = .default
    ) throws -> [MacActiveCaptureCandidate] {
        let urls = try fileManager.contentsOfDirectory(
            at: temporaryDirectoryURL,
            includingPropertiesForKeys: [.creationDateKey, .contentModificationDateKey],
            options: [.skipsHiddenFiles]
        )
        return urls.compactMap { candidate(at: $0) }
            .sorted { lhs, rhs in
                if lhs.createdAt == rhs.createdAt {
                    return lhs.url.lastPathComponent < rhs.url.lastPathComponent
                }
                return lhs.createdAt < rhs.createdAt
            }
    }

    /// Applies owner-only permissions through an already-open, non-following
    /// descriptor. Calling this immediately after AVFoundation starts and once
    /// again in its did-start callback closes the ordinary 0644 creation mode as
    /// early as the file exists without ever chmodding a symlink target.
    @discardableResult
    static func makeRecordingPrivate(at url: URL) -> Bool {
        guard captureID(forFileName: url.lastPathComponent) != nil else { return false }
        return makeOwnedRegularFilePrivate(at: url)
    }

    @discardableResult
    static func makeImportedFilePrivate(at url: URL) -> Bool {
        guard isGeneratedImportFileName(url.lastPathComponent) else { return false }
        return makeOwnedRegularFilePrivate(at: url)
    }

    /// Removes only disposable speech-bearing artifacts whose names and file
    /// metadata exactly match files generated by the upload/import paths. Active
    /// capture WAVs deliberately do not match either grammar and are recovered,
    /// never swept.
    static func cleanupDisposableSpeechArtifacts(
        in temporaryDirectoryURL: URL,
        fileManager: FileManager = .default
    ) -> MacPrivateTemporaryCleanupReport {
        let urls: [URL]
        do {
            urls = try fileManager.contentsOfDirectory(
                at: temporaryDirectoryURL,
                includingPropertiesForKeys: nil,
                options: [.skipsHiddenFiles]
            )
        } catch {
            return MacPrivateTemporaryCleanupReport(
                removedCount: 0,
                failureDescriptions: [error.localizedDescription]
            )
        }

        var removedCount = 0
        var failures: [String] = []
        for url in urls where isGeneratedDisposableFileName(url.lastPathComponent) {
            let descriptor = url.path.withCString {
                Darwin.open($0, O_RDONLY | O_NOFOLLOW | O_CLOEXEC)
            }
            guard descriptor >= 0 else { continue }

            var openedMetadata = stat()
            let isSafe = Darwin.fstat(descriptor, &openedMetadata) == 0
                && isOwnedSingleRegularFile(openedMetadata)
                && openedMetadata.st_mode & mode_t(0o777) == mode_t(0o600)
            guard isSafe else {
                Darwin.close(descriptor)
                continue
            }

            // Recheck the directory entry immediately before unlinking it. A
            // swapped path must never make cleanup act on a different inode.
            var currentMetadata = stat()
            let stillSameFile = url.path.withCString {
                Darwin.lstat($0, &currentMetadata) == 0
            }
                && currentMetadata.st_dev == openedMetadata.st_dev
                && currentMetadata.st_ino == openedMetadata.st_ino
                && isOwnedSingleRegularFile(currentMetadata)
                && currentMetadata.st_mode & mode_t(0o777) == mode_t(0o600)
            guard stillSameFile else {
                Darwin.close(descriptor)
                continue
            }

            let unlinkStatus = url.path.withCString { Darwin.unlink($0) }
            let unlinkError = errno
            Darwin.close(descriptor)
            if unlinkStatus == 0 {
                removedCount += 1
            } else {
                failures.append(
                    NSError(
                        domain: NSPOSIXErrorDomain,
                        code: Int(unlinkError),
                        userInfo: nil
                    ).localizedDescription
                )
            }
        }
        return MacPrivateTemporaryCleanupReport(
            removedCount: removedCount,
            failureDescriptions: failures
        )
    }

    private static func makeOwnedRegularFilePrivate(at url: URL) -> Bool {
        let descriptor = url.path.withCString {
            Darwin.open($0, O_RDONLY | O_NOFOLLOW | O_CLOEXEC)
        }
        guard descriptor >= 0 else { return false }
        defer { Darwin.close(descriptor) }

        var metadata = stat()
        guard
            Darwin.fstat(descriptor, &metadata) == 0,
            isOwnedSingleRegularFile(metadata),
            Darwin.fchmod(descriptor, mode_t(0o600)) == 0
        else {
            return false
        }
        return true
    }

    static func recover(
        from temporaryDirectoryURL: URL,
        into pendingAudioStore: MacPendingAudioStore,
        fileManager: FileManager = .default
    ) -> MacActiveCaptureRecoveryReport {
        let candidates: [MacActiveCaptureCandidate]
        do {
            candidates = try discover(in: temporaryDirectoryURL, fileManager: fileManager)
        } catch {
            return MacActiveCaptureRecoveryReport(
                recoveredRecords: [],
                failureDescriptions: [error.localizedDescription]
            )
        }

        var recoveredRecords: [MacPendingAudioRecord] = []
        var failures: [String] = []
        for candidate in candidates {
            do {
                // A cross-volume import must copy before it can unlink. If the
                // process stops in that narrow window, PendingAudio orphan
                // recovery sees the durable destination first and this scan
                // later sees the original capture. Collapse the two names only
                // after comparing their already-opened regular files byte for
                // byte; a same-ID collision with different bytes fails closed.
                if let existing = pendingAudioStore.record(withID: candidate.id) {
                    let durableURL = try pendingAudioStore.audioURL(for: existing)
                    guard try removeSourceIfIdentical(
                        candidate.url,
                        toDurableFileAt: durableURL
                    ) else {
                        failures.append(
                            "An interrupted recording reused recovery identifier \(candidate.id.uuidString), but its audio differed from the durable copy. Both files were preserved."
                        )
                        continue
                    }
                    recoveredRecords.append(existing)
                    continue
                }
                let staged = try pendingAudioStore.stage(
                    sourceURL: candidate.url,
                    id: candidate.id,
                    deviceName: "Recovered microphone capture",
                    recordingDuration: 0,
                    reason: "Recovered after Dictation Button closed during recording.",
                    createdAt: candidate.createdAt,
                    initialStatus: .waiting
                )
                recoveredRecords.append(staged)
            } catch {
                // `stage` is crash-safe. A commit failure can leave the moved
                // audio unindexed in the private journal, where normal launch
                // orphan recovery exposes it on the next run.
                failures.append(error.localizedDescription)
            }
        }
        return MacActiveCaptureRecoveryReport(
            recoveredRecords: recoveredRecords,
            failureDescriptions: failures
        )
    }

    /// Removes `sourceURL` only when it and `durableURL` are still the exact
    /// private, single-link regular files that were compared byte-for-byte.
    /// Holding both descriptors while rechecking the directory entries closes
    /// the compare/swap/unlink race; syncing the source directory makes the
    /// de-duplication itself durable before launch recovery reports success.
    private static func removeSourceIfIdentical(
        _ sourceURL: URL,
        toDurableFileAt durableURL: URL
    ) throws -> Bool {
        let sourceDirectoryURL = sourceURL.deletingLastPathComponent()
        let durableDirectoryURL = durableURL.deletingLastPathComponent()
        let sourceDirectory = try openOwnedDirectory(at: sourceDirectoryURL)
        defer { Darwin.close(sourceDirectory) }
        let durableDirectory = try openOwnedDirectory(at: durableDirectoryURL)
        defer { Darwin.close(durableDirectory) }

        let sourceName = sourceURL.lastPathComponent
        let durableName = durableURL.lastPathComponent
        guard
            !sourceName.isEmpty,
            sourceName != ".",
            sourceName != "..",
            !durableName.isEmpty,
            durableName != ".",
            durableName != ".."
        else {
            throw unsafeRecoveryFileError(path: sourceURL.path)
        }

        let sourceDescriptor = sourceName.withCString {
            Darwin.openat(sourceDirectory, $0, O_RDONLY | O_NOFOLLOW | O_CLOEXEC)
        }
        guard sourceDescriptor >= 0 else { throw posixError(path: sourceURL.path) }
        defer { Darwin.close(sourceDescriptor) }
        let durableDescriptor = durableName.withCString {
            Darwin.openat(durableDirectory, $0, O_RDONLY | O_NOFOLLOW | O_CLOEXEC)
        }
        guard durableDescriptor >= 0 else { throw posixError(path: durableURL.path) }
        defer { Darwin.close(durableDescriptor) }

        var sourceStatus = stat()
        var durableStatus = stat()
        guard
            Darwin.fstat(sourceDescriptor, &sourceStatus) == 0,
            Darwin.fstat(durableDescriptor, &durableStatus) == 0
        else {
            throw posixError(path: sourceURL.path)
        }
        guard
            isOwnedSingleRegularFile(sourceStatus),
            isOwnedSingleRegularFile(durableStatus),
            sourceStatus.st_mode & mode_t(0o777) == mode_t(0o600),
            durableStatus.st_mode & mode_t(0o777) == mode_t(0o600)
        else {
            throw unsafeRecoveryFileError(path: sourceURL.path)
        }
        guard sourceStatus.st_size == durableStatus.st_size else { return false }
        guard try descriptorsHaveEqualContents(
            sourceDescriptor,
            durableDescriptor,
            path: sourceURL.path
        ) else {
            return false
        }

        guard
            entryStillNamesOpenedFile(
                sourceName,
                in: sourceDirectory,
                openedStatus: sourceStatus
            ),
            entryStillNamesOpenedFile(
                durableName,
                in: durableDirectory,
                openedStatus: durableStatus
            )
        else {
            throw unsafeRecoveryFileError(path: sourceURL.path)
        }
        guard sourceName.withCString({ Darwin.unlinkat(sourceDirectory, $0, 0) }) == 0 else {
            throw posixError(path: sourceURL.path)
        }
        guard Darwin.fsync(sourceDirectory) == 0 else {
            throw posixError(path: sourceDirectoryURL.path)
        }
        return true
    }

    private static func openOwnedDirectory(at url: URL) throws -> Int32 {
        let descriptor = url.path.withCString {
            Darwin.open($0, O_RDONLY | O_DIRECTORY | O_NOFOLLOW | O_CLOEXEC)
        }
        guard descriptor >= 0 else { throw posixError(path: url.path) }
        var metadata = stat()
        guard
            Darwin.fstat(descriptor, &metadata) == 0,
            metadata.st_mode & mode_t(S_IFMT) == mode_t(S_IFDIR),
            metadata.st_uid == Darwin.geteuid()
        else {
            Darwin.close(descriptor)
            throw unsafeRecoveryFileError(path: url.path)
        }
        return descriptor
    }

    private static func entryStillNamesOpenedFile(
        _ name: String,
        in directory: Int32,
        openedStatus: stat
    ) -> Bool {
        var currentStatus = stat()
        return name.withCString {
            Darwin.fstatat(directory, $0, &currentStatus, AT_SYMLINK_NOFOLLOW) == 0
        }
            && currentStatus.st_dev == openedStatus.st_dev
            && currentStatus.st_ino == openedStatus.st_ino
            && isOwnedSingleRegularFile(currentStatus)
            && currentStatus.st_mode & mode_t(0o777) == mode_t(0o600)
    }

    private static func descriptorsHaveEqualContents(
        _ lhs: Int32,
        _ rhs: Int32,
        path: String
    ) throws -> Bool {
        var lhsBuffer = [UInt8](repeating: 0, count: 64 * 1024)
        var rhsBuffer = [UInt8](repeating: 0, count: 64 * 1024)
        while true {
            let lhsCount = try readChunk(from: lhs, into: &lhsBuffer, path: path)
            let rhsCount = try readChunk(from: rhs, into: &rhsBuffer, path: path)
            guard lhsCount == rhsCount else { return false }
            guard lhsCount > 0 else { return true }
            guard lhsBuffer[..<lhsCount].elementsEqual(rhsBuffer[..<rhsCount]) else {
                return false
            }
        }
    }

    private static func readChunk(
        from descriptor: Int32,
        into buffer: inout [UInt8],
        path: String
    ) throws -> Int {
        while true {
            let count = buffer.withUnsafeMutableBytes {
                Darwin.read(descriptor, $0.baseAddress, $0.count)
            }
            if count >= 0 { return count }
            if errno == EINTR { continue }
            throw posixError(path: path)
        }
    }

    private static func posixError(path: String, code: Int32 = errno) -> NSError {
        NSError(
            domain: NSPOSIXErrorDomain,
            code: Int(code),
            userInfo: [NSFilePathErrorKey: path]
        )
    }

    private static func unsafeRecoveryFileError(path: String) -> NSError {
        NSError(
            domain: NSPOSIXErrorDomain,
            code: Int(ELOOP),
            userInfo: [
                NSFilePathErrorKey: path,
                NSLocalizedDescriptionKey: "An interrupted recording changed while Dictation Button was recovering it.",
            ]
        )
    }

    private static func candidate(at url: URL) -> MacActiveCaptureCandidate? {
        guard let id = captureID(forFileName: url.lastPathComponent) else { return nil }
        let descriptor = url.path.withCString {
            Darwin.open($0, O_RDONLY | O_NOFOLLOW | O_CLOEXEC)
        }
        guard descriptor >= 0 else { return nil }
        defer { Darwin.close(descriptor) }

        var metadata = stat()
        guard
            Darwin.fstat(descriptor, &metadata) == 0,
            isOwnedSingleRegularFile(metadata),
            metadata.st_mode & mode_t(0o777) == mode_t(0o600),
            metadata.st_size > minimumWAVHeaderSize
        else {
            return nil
        }

        var header = [UInt8](repeating: 0, count: 12)
        let bytesRead = header.withUnsafeMutableBytes { buffer in
            Darwin.read(descriptor, buffer.baseAddress, buffer.count)
        }
        guard
            bytesRead == header.count,
            Array(header.prefix(4)) == Array("RIFF".utf8),
            Array(header.dropFirst(8).prefix(4)) == Array("WAVE".utf8)
        else {
            return nil
        }

        let values = try? url.resourceValues(
            forKeys: [.creationDateKey, .contentModificationDateKey]
        )
        return MacActiveCaptureCandidate(
            id: id,
            url: url,
            createdAt: values?.creationDate ?? values?.contentModificationDate ?? Date()
        )
    }

    static func captureID(forFileName fileName: String) -> UUID? {
        guard fileName.hasPrefix(prefix), fileName.hasSuffix(suffix) else { return nil }
        let idStart = fileName.index(fileName.startIndex, offsetBy: prefix.count)
        let idEnd = fileName.index(fileName.endIndex, offsetBy: -suffix.count)
        let rawID = String(fileName[idStart..<idEnd])
        guard let id = UUID(uuidString: rawID) else { return nil }
        guard fileName == "\(prefix)\(id.uuidString)\(suffix)" else { return nil }
        return id
    }

    private static func isGeneratedDisposableFileName(_ fileName: String) -> Bool {
        isGeneratedUploadFileName(fileName) || isGeneratedImportFileName(fileName)
    }

    private static func isGeneratedUploadFileName(_ fileName: String) -> Bool {
        generatedID(
            in: fileName,
            prefix: uploadPrefix,
            suffix: uploadSuffix
        ) != nil
    }

    private static func isGeneratedImportFileName(_ fileName: String) -> Bool {
        guard fileName.hasPrefix(importPrefix) else { return false }
        let remainder = fileName.dropFirst(importPrefix.count)
        guard let dot = remainder.firstIndex(of: ".") else { return false }
        let rawID = String(remainder[..<dot])
        let extensionStart = remainder.index(after: dot)
        let fileExtension = String(remainder[extensionStart...])
        guard
            let id = UUID(uuidString: rawID),
            rawID == id.uuidString,
            importExtensions.contains(fileExtension.lowercased())
        else {
            return false
        }
        return fileName == "\(importPrefix)\(id.uuidString).\(fileExtension)"
    }

    private static func generatedID(
        in fileName: String,
        prefix: String,
        suffix: String
    ) -> UUID? {
        guard fileName.hasPrefix(prefix), fileName.hasSuffix(suffix) else { return nil }
        let idStart = fileName.index(fileName.startIndex, offsetBy: prefix.count)
        let idEnd = fileName.index(fileName.endIndex, offsetBy: -suffix.count)
        let rawID = String(fileName[idStart..<idEnd])
        guard let id = UUID(uuidString: rawID), rawID == id.uuidString else { return nil }
        guard fileName == "\(prefix)\(id.uuidString)\(suffix)" else { return nil }
        return id
    }

    private static func isOwnedSingleRegularFile(_ metadata: stat) -> Bool {
        metadata.st_mode & mode_t(S_IFMT) == mode_t(S_IFREG)
            && metadata.st_uid == Darwin.geteuid()
            && metadata.st_nlink == 1
    }
}
